sudo: required
dist: trusty
language: cpp

os:
  - linux
 
notifications:
  email: 
    recipients:
      - cgnerds@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

compiler:
  - gcc

before_install:
  - env | sort

install:
  - script/install-deps-linux.sh

before_script:
  # OpenCV
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..
  # THIS
  - mkdir build
  - cd build
  - cmake ..
  
script: make

# right now only build the master branch
branches:
  only:
    - master