sudo: required
dist: trusty
language: cpp

os:
  - linux
 
notifications:
  email: 
    recipients:
      - cgnerds@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

compiler:
  - gcc

before_install:
  - env | sort

install:
  - sudo apt-get install -qq build-essential libgtk2.0-dev libvtk5-dev libjpeg-dev libtiff4-dev libjasper-dev libopenexr-dev libtbb-dev qtdeclarative5-dev qt5-qmake libqglviewer-dev libeigen3-dev libsuitesparse-dev libboost-all-dev

before_script:

  # Sophus
  - git clone https://github.com/strasdat/Sophus
  - cd Sophus
  - git checkout a621ff
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - cd ../..

  # OpenCV
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..

  # g2o
  - git clone https://github.com/RainerKuemmerle/g2o.git
  - cd g2o
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..
  
  # DBow3
  - git clone https://github.com/rmsalinas/DBow3.git
  - cd DBow3
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

  # THIS
  - mkdir build
  - cd build
  - cmake ..
  
script: make

# right now only build the master branch
branches:
  only:
    - master
